### ISSUE TITLE
help

### ISSUE THREAD

**Issue by XENOGENGOD** [j0ach1mmall3/PermissionsShop#1] opened 2015-11-06 20:12 UTC
20:11:19 [ERROR] Could not pass event InventoryClickEvent to PermissionsShop v2.1.4
20:11:19 org.bukkit.event.EventException
20:11:20 at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot_server.jar:git-Spigot-5f38d38-18fbb24]
20:11:20 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot_server.jar:git-Spigot-5f38d38-18fbb24]
20:11:20 at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot_server.jar:git-Spigot-5f38d38-18fbb24]
20:11:20 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot_server.jar:git-Spigot-5f38d38-18fbb24]
20:11:20 at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1630) [spigot_server.jar:git-Spigot-5f38d38-18fbb24]
20:11:20 at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31) [spigot_server.jar:git-Spigot-5f38d38-18fbb24]
20:11:20 at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9) [spigot_server.jar:git-Spigot-5f38d38-18fbb24]
20:11:20 at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot_server.jar:git-Spigot-5f38d38-18fbb24]
20:11:20 at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_65]
20:11:20 at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_65]
20:11:20 at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot_server.jar:git-Spigot-5f38d38-18fbb24]
20:11:20 at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot_server.jar:git-Spigot-5f38d38-18fbb24]
20:11:20 at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot_server.jar:git-Spigot-5f38d38-18fbb24]
20:11:20 at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot_server.jar:git-Spigot-5f38d38-18fbb24]
20:11:20 at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot_server.jar:git-Spigot-5f38d38-18fbb24]
20:11:20 at java.lang.Thread.run(Unknown Source) [?:1.8.0_65]
20:11:20 Caused by: java.lang.IllegalArgumentException: Item cannot be null
20:11:20 at org.apache.commons.lang.Validate.noNullElements(Validate.java:364) ~[spigot_server.jar:git-Spigot-5f38d38-18fbb24]
20:11:20 at org.bukkit.craftbukkit.v1_8_R3.inventory.CraftInventory.addItem(CraftInventory.java:265) ~[spigot_server.jar:git-Spigot-5f38d38-18fbb24]
20:11:20 at com.j0ach1mmall3.jlib.inventory.GUI.<init>(GUI.java:30) ~[?:?]
20:11:20 at com.j0ach1mmall3.jlib.inventory.GUI.<init>(GUI.java:40) ~[?:?]
20:11:20 at com.j0ach1mmall3.permissionsshop.listeners.PlayerListener.handlePurchase(PlayerListener.java:176) ~[?:?]
20:11:20 at com.j0ach1mmall3.permissionsshop.listeners.PlayerListener.onInventoryClick(PlayerListener.java:132) ~[?:?]
20:11:20 at sun.reflect.GeneratedMethodAccessor16.invoke(Unknown Source) ~[?:?]
20:11:20 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
20:11:20 at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_65]
20:11:20 at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot_server.jar:git-Spigot-5f38d38-18fbb24]
20:11:20 ... 15 more

**Comment by j0ach1mmall3** [comment] 2015-11-06 20:37
Are you on the latest JLib? 4.0.0

**Comment by jianluca1** [comment] 2015-11-07 16:57
I have the same issue too. I am using JLib 4.0.0

**Comment by j0ach1mmall3** [comment] 2015-11-08 15:21
Duplicate of #2

**Closed by j0ach1mmall3** 2015-11-08 15:21 UTC
Labels: duplicate
